version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          SECRET_KEY: abcd
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: sudo chown -R circleci:circleci /usr/local/man
      - run: sudo pip install -e .[dev,standalone]
      - run: simplestats test
      - store_test_results:
          path: test-results

general:
  branches:
    ignore:
      - gh-pages
