version: 2.1

general:
  branches:
    ignore:
      - gh-pages

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          SECRET_KEY: abcd
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          CELERY_BROKER_URL: redis://redis:6379/0
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      - image: redis
    steps:
      - checkout
      - run: mkdir -p test-results
      - run: python3 -m venv .venv
      - run: .venv/bin/pip install -r docker/requirements.txt
      - run: .venv/bin/pip install -e .[dev,standalone]
      - run: .venv/bin/quickstats test -v 2 --with-xunit --xunit-file test-results/nosetests.xml --noinput
      - store_test_results:
          path: test-results
